validation: sovereign
version: 1
accounts:
  - name: validator-1
    coins:
      - 20000000umy
    mnemonic: advice farm scrap basket knock wish tattoo order dog arrange obey metal day romance drift busy short chronic impulse keen kiwi lawn answer short
  - name: validator-2
    coins:
      - 20000000umy
    mnemonic: clean kit shoe brief teach settle stuff enlist build walk fly battle staff scare usage cry company decorate train cute list card sun salad
  - name: validator-3
    coins:
      - 20000000umy
    mnemonic: already guilt lawsuit crime silent practice orchard garment electric month during goddess celery advice slim term please survey stool flight wash provide thunder planet
faucet:
  name: validator-1
  coins:
    - 1000000umy
  coins_max:
    - 1umy
genesis:
  chain_id: mychain-devnet
  genesis_time: "2024-05-23T02:56:42.736309Z"
  app_state:
    mint:
      params:
        mint_denom: umy
    staking:
      params:
        bond_denom: umy
    gov:
      params:
        expedited_min_deposit:
          - amount: "20000000"
            denom: umy
        min_deposit:
          - amount: "10000000"
            denom: umy
    crisis:
      constant_fee:
        amount: "10000000"
        denom: umy

validators:
  - name: validator-3
    bonded: 10000000umy
    config:
      moniker: mychain-devnet-validator-3
      # validator-2/3만 필요
      p2p:
        laddr: tcp://192.168.0.237:26656
        addr_book_strict: false
        seeds: e7820c75295828ea489c30cb1ae347a32d05ac4c@192.168.0.209:26656
        seed_mode: false
